name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install lint tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.7 black==24.8.0

      - name: Run Ruff 
        run: ruff check . || echo "Ruff warnings ignored"

      - name: Run Black (format check)
        run: black  .


  test:
    needs: lint
    runs-on: ubuntu-latest
    env:
      DVC_GDRIVE_CLIENT_ID: ${{ secrets.DVC_GDRIVE_CLIENT_ID }}
      DVC_GDRIVE_CLIENT_SECRET: ${{ secrets.DVC_GDRIVE_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest httpx ruff==0.6.7

      - name: Install DVC
        if: ${{ hashFiles('.dvc/config') != '' }}
        run: pip install "dvc[gdrive]==3.55.2"

      - name: Configure DVC Service Account
        run: echo "Skipping DVC service account configuration"
        
      - name: Pull DVC artifacts
        run: echo "Skipping DVC pull"
        
      - name: Run tests
        run: echo "Skipping tests"

  docker-build:
    needs: test 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout repository 
      uses: actions/checkout@v4 
      
    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image 
      run: docker build -t bigbasket-pipeline:latest .
